<link href="css/components/signin.css" rel="stylesheet" type="text/css">   
<div class="account-container login">

	<div class="content clearfix">

		<form action="<?php print $this->form->getAction();?>"  method="<?php print $this->form->getMethod();?>">

			<h1>Área Restrita</h1>

			<div class="login-fields">

				<p>Logue-se no sistema utilizando um e-mail registrado:</p>

				<div class="field">
					<label for="email">E-mail:</label>
					<?php print $this->form->email; ?>
				</div> <!-- /field -->

				<div class="field">
					<label for="senha">Senha:</label>
					<?php print $this->form->senha; ?>
				</div> <!-- /password -->

			</div> <!-- /login-fields -->

			<div class="login-actions">

				<input type="submit" class="button btn btn-secondary btn-large" value="Entrar"/>

			</div> <!-- .actions -->
		</form>

	</div> <!-- /content -->

</div> <!-- /account-container -->