language: php
php:
	- 5.4
env:
	- DB=mysql

before_script:
	- mysql -e "create database if not exists transportadora;" -u root
	- mysql -e "use transportadora;" -u root
	- mysql transportadora < ./banco/transportadora.sql