		</div> <!-- /.row -->

	</div> <!-- /.container -->

</div> <!-- /#content -->

<div id="footer">

	<div class="container">

		<p>&copy; 2012 - Todos os direitos reservados.<br/>
			Produzido por Deyvison Rocha</p>

	</div> <!-- /.container -->

</div> <!-- /#footer -->

<script type="text/javascript">
	$(function () {

		$(".btnExcluir").live('click', function () {
			if(confirm('Você deseja realmente excluir este item?')) {
				return true;
			} else {
				return false;
			}
		});
		
	});
</script>