<script type="text/javascript">
	$(function () {
		// formata os campos data
		$("input[name*=data]").setMask('date', {placeholder: " "}).datepicker();;

		// dados da fatura
		$("input[name*=valor], input[name*=desconto]").setMask('decimal', {placeholder: " "});

		// autocomplete
		$("#destino_cpf_cnpj").autocomplete(
			{
				minLength: 2,
				selectFirst: true,
				source: urlSite + "/ordem-servico/buscar-cliente",
				select: function (event, ui) {
					$("#id_cliente_destino").val(ui.item.id_cliente);
					$("#destino_razao_social").val(ui.item.razao_social);
					$("#destino_endereco").val(ui.item.endereco);
					$("#destino_numero").val(ui.item.numero);
					$("#destino_complemento").val(ui.item.complemento);
					$("#destino_bairro").val(ui.item.bairro);
					$("#destino_cidade").val(ui.item.cidade);
					$("#destino_uf").val(ui.item.uf);
					$("#destino_cep").val(ui.item.cep);
					$("#destino_contato").val(ui.item.contato);
					$("#destino_cpf_cnpj").val('').val(ui.item.cpf_cnpj);
				}
			}
		);

		$("#origem_cpf_cnpj").autocomplete(
			{
				minLength: 2,
				selectFirst: true,
				source: urlSite + "/ordem-servico/buscar-cliente",
				select: function (event, ui) {
					$("#id_cliente_origem").val(ui.item.id_cliente);
					$("#origem_razao_social").val(ui.item.razao_social);
					$("#origem_endereco").val(ui.item.endereco);
					$("#origem_numero").val(ui.item.numero);
					$("#origem_complemento").val(ui.item.complemento);
					$("#origem_bairro").val(ui.item.bairro);
					$("#origem_cidade").val(ui.item.cidade);
					$("#origem_uf").val(ui.item.uf);
					$("#origem_cep").val(ui.item.cep);
					$("#origem_contato").val(ui.item.contato);
					$("#origem_cpf_cnpj").val('').val(ui.item.cpf_cnpj);
				}
			}
		);
	});
</script>

<form action="<?= $this->form->getAction() ?>" id="formulario-fatura" class="form-horizontal" novalidate="novalidate" method="<?= $this->form->getMethod() ?>">
	<?= $this->form->id_ordem_servico ?>
	<!-- DADOS ORIGEM -->
	<div class="span6">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-map-marker"></i>
					Dados de Origem
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<?= $this->form->id_cliente_origem ?>
					<div class="control-group">
						<label class="control-label" for="origem_cpf_cnpj">CNPJ/CPF</label>
						<div class="controls">
							<?= $this->form->origem_cpf_cnpj ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_razao_social">Razão Social</label>
						<div class="controls">
							<?= $this->form->origem_razao_social ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_endereco">Endereço</label>
						<div class="controls">
							<?= $this->form->origem_endereco ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_numero">Número</label>
						<div class="controls">
							<?= $this->form->origem_numero ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_complemento">Complemento</label>
						<div class="controls">
							<?= $this->form->origem_complemento ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_bairro">Bairro</label>
						<div class="controls">
							<?= $this->form->origem_bairro ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_cidade">Cidade</label>
						<div class="controls">
							<?= $this->form->origem_cidade ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_uf">UF</label>
						<div class="controls">
							<?= $this->form->origem_uf ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_contato">Contato</label>
						<div class="controls">
							<?= $this->form->origem_contato ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="origem_fone">Telefone</label>
						<div class="controls">
							<?= $this->form->origem_fone ?>
						</div>
					</div>
				</fieldset>
			</div> <!-- /widget-content -->
		</div>
	</div>

	<!-- DADOS DESTINO -->
	<div class="span6">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-road"></i>
					Dados de Destino
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<?= $this->form->id_cliente_destino ?>
					<div class="control-group">
						<label class="control-label" for="destino_cpf_cnpj">CNPJ/CPF</label>
						<div class="controls">
							<?= $this->form->destino_cpf_cnpj ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_razao_social">Razão Social</label>
						<div class="controls">
							<?= $this->form->destino_razao_social ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_endereco">Endereço</label>
						<div class="controls">
							<?= $this->form->destino_endereco ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_numero">Número</label>
						<div class="controls">
							<?= $this->form->destino_numero ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_complemento">Complemento</label>
						<div class="controls">
							<?= $this->form->destino_complemento ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_bairro">Bairro</label>
						<div class="controls">
							<?= $this->form->destino_bairro ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_cidade">Cidade</label>
						<div class="controls">
							<?= $this->form->destino_cidade ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_uf">UF</label>
						<div class="controls">
							<?= $this->form->destino_uf ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_contato">Contato</label>
						<div class="controls">
							<?= $this->form->destino_contato ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="destino_fone">Telefone</label>
						<div class="controls">
							<?= $this->form->destino_fone ?>
						</div>
					</div>
				</fieldset>
			</div> <!-- /widget-content -->
		</div>
	</div>


	<!-- DADOS DO ORÇAMENTO -->
	<div class="span4">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-pencil"></i>
					Dados da Ordem de Serviço
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<div class="control-group">
						<label class="control-label" for="data">Data Execução</label>
						<div class="controls">
							<?= $this->form->data_execucao ?>
							<span class="help-inline">DD/MM/YYYY</span>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="km_inicial">KM Inicial</label>
						<div class="controls">
							<?= $this->form->km_inicial ?>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="km_final">KM Final</label>
						<div class="controls">
							<?= $this->form->km_final ?>
						</div>
					</div>
				</fieldset>
			</div>
		</div>
	</div>

	<!-- SERVIÇOS A EXECUTAR -->
	<div class="span8">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-comment"></i>
					Serviço a Executar
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<div class="control-group">
						<label class="control-label" for="titulo_servico">Titulo do Serviço</label>
						<div class="controls">
							<?= $this->form->titulo_servico ?>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="descricao_servico">Descrição do Serviço</label>
						<div class="controls">
							<?= $this->form->descricao_servico ?>
						</div>
					</div>
				</fieldset>
			</div> <!-- /widget-content -->
		</div>
	</div>


	<div class="span12">
		<div class="widget widget-table" align='center'>
			<div class="widget-header">
				<h3>
					<i class="icon-list-alt"></i>
					Preço & Observação
			    </h3>
			</div>
			<div class="widget-content">
				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Frete</th>
							<th>Seguro</th>
							<th>Imposto</th>
							<th>Valor Total</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<div class="input-prepend input-append">
									<span class="add-on">R$</span><?= $this->form->valor_frete ?>
								</div>
							</td>
							<td>
								<div class="input-prepend input-append">
									<span class="add-on">R$</span><?= $this->form->valor_seguro ?>
								</div>
							</td>
							<td>
								<div class="input-prepend input-append">
									<span class="add-on">R$</span><?= $this->form->valor_imposto ?>
								</div>
							</td>
							<td>
								<div class="input-prepend input-append">
									<span class="add-on">R$</span><input class="input-medium" id="valor_total" size="16" type="text" name="valor_total">
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<!-- OBSERVAÇÃO -->
	<div class="span12">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-comment"></i>
					Observação
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<div class="control-group">
						<?= $this->form->observacao ?>
					</div>
				</fieldset>
			</div> <!-- /widget-content -->
		</div>
	</div>

	<div class="span12">
		<div class="widget" align='center'>
			<div class="widget-header">
				<h3>
					<i class="icon-user"></i>
					Ação
			    </h3>
			</div>
			<div class="widget-content">
				<button type="submit" class="btn btn-primary btn-large">
					<i class="icon-file"></i>
					Salvar Orçamento
				</button>
				<button type="reset" class="btn btn-large btn-danger">
					<i class="icon-remove"></i>
					Cancelar
				</button>
			</div>
		</div>
	</div>
</form>
