<div class="span12">
	<h3>Ordem de Serviço</h3>

</div>

<div class="span12">
	<div class="widget widget-table" align='center'>
		<div class="widget-header">
			<h3>
				<i class="icon-list-alt"></i>
				Listagem
		    </h3>
		    <div class="widget-actions">
				<div class="btn-group">
                    <a class="btn btn-medium" href="<?php print $this->url(array('controller' => 'ordem-servico', 'action' => 'form'), null, true); ?>">
                        <i class="icon-plus"></i>
                        Cadastrar
                    </a>
                </div>
			</div> <!-- /.widget-actions -->
		</div>


		<div class="widget-content">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th width="5%"><div align='center'>#</div></th>
						<th width="40%">Cliente</th>
						<th>Data de Emissão</th>
						<th>Data de Vencimento</th>
						<th>Nota Fiscal</th>
						<th>Valor</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>1</td>
						<td>Deyvison Rocha</td>
						<td>31/07/2012</td>
						<td>10/08/2012</td>
						<td>123456-5</td>
						<td>R$ 5.350,00</td>
						<td>
							<a href="" class="btn btn-primary btn-mini">
								<i class="icon-pencil"></i>
								Editar
							</a>
							<a href="" class="btn btn-danger btn-mini">
								<i class="icon-trash"></i>
								Excluir
							</a>
						</td>
					</tr>
				</tbody>
				<tfoot>
				</tfoot>
			</table>
		</div>
	</div>
</div>