<script type="text/javascript">
	$(function () {
		$("#tipo_cliente").change(function () {
			var elemento = $(this);
			var valor = elemento.val();
			if (valor == "PJ") {
				$(".pj").show();
				$(".pf").hide();
				$("label[for=razao_social]").text('Razão Social');
				$("input[name=razao_social]").attr('placeholder', 'Razão Social');
				$("input[name=cpf_cnpj]").attr('placeholder', 'CNPJ');
				$("label[for=cpf_cnpj]").text('CNPJ');
			} else {
				$(".pj").hide();
				$(".pf").show();
				$("label[for=razao_social]").text('Nome Completo');
				$("input[name=razao_social]").attr('placeholder', 'Nome Completo');
				$("input[name=cpf_cnpj]").attr('placeholder', 'CPF');
				$("label[for=cpf_cnpj]").text('CPF');
			}
		});

		$(".pj").hide(); // pessoa física como default
	});
</script>

<form action="<?= $this->form->getAction() ?>" id="formulario-cliente" class="form-horizontal" novalidate="novalidate" method="<?= $this->form->getMethod() ?>">

	<!-- DADOS ORIGEM -->
	<div class="span6">
		<div id="validation" class="widget highlight widget-form">
			<div class="widget-header">
				<h3>
					<i class="icon-user"></i>
					Dados do Cliente
			    </h3>
			</div>
			<div class="widget-content">
				<fieldset>
					<input id="id_cliente" type="hidden" name="id_cliente">
					
					<div class="control-group">
						<label class="control-label" for="tipo_cliente">Tipo do Cliente</label>
						<div class="controls">
							<?= $this->form->tipo_cliente ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="cpf_cnpj">CPF</label>
						<div class="controls">
							<?= $this->form->cpf_cnpj ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="razao_social">Nome Completo</label>
						<div class="controls">
							<?= $this->form->razao_social ?>
						</div>
					</div>

					<div class="control-group pj">
						<label class="control-label" for="nome_fantasia">Nome Fantasia</label>
						<div class="controls">
							<?= $this->form->nome_fantasia ?>
						</div>
					</div>

					<div class="control-group pj">
						<label class="control-label" for="contato">Contato</label>
						<div class="controls">
							<?= $this->form->contato ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="telefone1">Telefone</label>
						<div class="controls">
							<?= $this->form->telefone1 ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="telefone2">Celular</label>
						<div class="controls">
							<?= $this->form->telefone2 ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="site">Site</label>
						<div class="controls">
							<?= $this->form->site ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="email">E-mail</label>
						<div class="controls">
							<?= $this->form->email ?>
						</div>
					</div>

					<div class="control-group pf">
						<label class="control-label" for="sexo">Sexo</label>
						<div class="controls">
							<?= $this->form->sexo ?>
						</div>
					</div>

					<div class="control-group pj">
						<label class="control-label" for="inscricao_estadual">Inscrição Estadual</label>
						<div class="controls">
							<?= $this->form->inscricao_estadual ?>
						</div>
					</div>

					<div class="control-group pj">
						<label class="control-label" for="inscricao_municipal">Inscrição Municipal</label>
						<div class="controls">
							<?= $this->form->inscricao_municipal ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="ativo">Ativo</label>
						<div class="controls">
							<?= $this->form->ativo ?>
						</div>
					</div>
				</fieldset>
			</div> <!-- /widget-content -->
		</div>
	</div>

	<div class="span6">
		<div class="widget">
			<div class="widget-header">
				<h3>
					<i class="icon-road"></i>
					Dados do Endereço
				</h3>
			</div>

			<div class="widget-content">
				<fieldset>
					<div class="control-group">
						<label class="control-label" for="cep">CEP</label>
						<div class="controls">
							<?= $this->form->cep ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="endereco">Endereço</label>
						<div class="controls">
							<?= $this->form->endereco ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="numero">Número</label>
						<div class="controls">
							<?= $this->form->numero ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="complemento">Complemento</label>
						<div class="controls">
							<?= $this->form->complemento ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="bairro">Bairro</label>
						<div class="controls">
							<?= $this->form->bairro ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="cidade">Cidade</label>
						<div class="controls">
							<?= $this->form->cidade ?>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="uf">UF</label>
						<div class="controls">
							<?= $this->form->uf ?>
						</div>
					</div>
				</fieldset>
			</div>
		</div>
	</div>

	<div class="span12">
		<div class="widget" align='center'>
			<div class="widget-header">
				<h3>
					<i class="icon-user"></i>
					Ação
			    </h3>
			</div>
			<div class="widget-content">
				<button type="submit" class="btn btn-primary btn-large">
					<i class="icon-file"></i>
					Salvar Cliente
				</button>
				<button type="reset" class="btn btn-large btn-danger">
					<i class="icon-remove"></i>
					Cancelar
				</button>
			</div>
		</div>
	</div>
</form>
