<div class="span12">
	<h3>Clientes</h3>

</div>

<div class="span12">
	<div class="widget widget-table" align='center'>
		<div class="widget-header">
			<h3>
				<i class="icon-list-alt"></i>
				Listagem
		    </h3>
		    <div class="widget-actions">
				<div class="btn-group">
                    <a class="btn btn-medium" href="<?= $this->url(array('controller' => 'cliente', 'action' => 'form'), null, true); ?>">
                        <i class="icon-plus"></i>
                        Cadastrar
                    </a>
                </div>
			</div> <!-- /.widget-actions -->
		</div>


		<div class="widget-content">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th width="5%"><div align='center'>#</div></th>
						<th width="30%">Razão Social / Nome Fantasia</th>
						<th>Tipo Cliente</th>
						<th>CPF/CNPJ</th>
						<th>Telefone</th>
						<th>E-mail</th>
						<th width="13%">Ação</th>
					</tr>
				</thead>
				<tbody>
					<?php
					if (count($this->dados) > 0) :
						foreach ($this->dados as $valor):
					?>
					<tr>
						<td><div align='center'><?= $valor['id_cliente'] ?></div></td>
						<td><?= $valor['razao_social'] ?></td>
						<td><?= $valor['tipo_cliente'] ?></td>
						<td><?= $valor['cpf_cnpj'] ?></td>
						<td><?= $valor['telefone1'] ?></td>
						<td><?= $valor['email'] ?></td>
						<td>
							<a href="<?= $this->url(array('controller' => 'cliente', 'action' => 'form', 'id' => $valor['id_cliente']),null,true); ?>" class="btn btn-primary btn-mini">
								<i class="icon-print"></i>
								Editar
							</a>
							<a href="<?= $this->url(array('controller' => 'cliente', 'action' => 'excluir', 'id' => $valor['id_cliente']),null,true); ?>" class="btn btn-danger btn-mini">
								<i class="icon-trash"></i>
								Excluir
							</a>
						</td>
					</tr>
					<?php
						endforeach;
					else:
					?>
					<tr>
						<td colspan='7'>
							<div align='center'>
								Não foi encontrado nenhum cliente cadastrado.
							</div>
						</td>
					</tr>
					<?
					endif;
					?>
				</tbody>
				<tfoot>
				</tfoot>
			</table>
		</div>
	</div>
</div>