<style type='text/css'>
.tabela_a4 {
	width: 595px;
	height: 842px;
	border: 1px solid #000;
	border-collapse: collapse;
	padding: 0;
	margin: 0;
	font-size: 13px;
}
.tabela_a4 tr {
	vertical-align: top;
}
.info_cliente {
	padding: 0;
	margin: 0;
	border: 0;
	font-size: 12px;
}

</style>
<table border='1' class='tabela_a4'>
	<tr height='120px'>
		<td colspan='4'>
			LOGOMARCA
		</td>
		<td colspan='2'>
			TEXTO
		</td>
	</tr>
	<tr>
		<td colspan='5' height="75">
			<div clas='linha_um' style='position: absolute; margin-left: 6px; margin-top:40px; width: 500px'>
				<div class='valor_fatura' style='text-align: center; float: left; width:95px;'>
					<?php print Funcoes::formataValor($this->fatura->valor_total); ?>
				</div>

				<div class='numero_fatura'style='text-align: center; float: left; width:95px;'>
					<?php print $this->fatura->numero_fatura; ?>
				</div>
				<div class='valor_duplicata'style='text-align: center; float: left; width:95px;'>
					<?php print Funcoes::formataValor($this->fatura->valor_duplicata); ?>
				</div>
				<div class='numero_duplicata'style='text-align: center; float: left; width:95px;'>
					<?php print $this->fatura->numero_duplicata; ?>
				</div>
				<div class='data_vencimento1'style='text-align: center; float: left; width:95px;'>
					<?php print Funcoes::formataData($this->fatura->data_vencimento); ?>
				</div>
			</div>
		</td>
		<td></td>
	</tr>
	<tr height="60">
		<td rowspan='5' width="100"></td>
		<td colspan='4'>
			<div clas='linha_dois' style='position: absolute; margin: 3; width: 385px;'>
				<div class='valor_fatura' style='float: left; width: 180px; margin-left: 70px;'>
					R$ 10.000.00<?php print ($this->fatura->desconto == "0.00" ? '' : 'R$ '.Funcoes::formataValor($this->fatura->desconto)) ?>
				</div>

				<div class='numero_fatura'style='float: left; width:130px;'>
					<?php print ($this->fatura->desconto == "" ? '' : Funcoes::formataData($this->fatura->data_pagamento)) ?>
				</div>
				<div class='valor_duplicata'style='margin-left: 110px;float: left; margin-top:8px'>
					<?php print $this->fatura->condicoes_especiais ?>
				</div>
			</div>
		</td>
		<td></td>
	</tr>
	<tr>
		<td colspan='5'>
			<div style='width: 485px; border:1px solid #000;'>
				<div class='nome' style="margin-left: 85px;display: block;">
					<?php print $this->cliente->razao_social ?>
				</div>
				<div class='endereco' style="margin-left: 85px; margin-top:3px;display: block;">
					<?php print $this->cliente->endereco ?>
				</div>
				<div class='municipio' style="margin-left: 85px; margin-top:3px; width: 220px; border:1px solid #000">
					<?php print $this->cliente->cidade ?>
				</div>
				<div class='estado' style="position: relative; float:left;width: 20px; border:1px solid #000;">
					<?php print $this->cliente->uf ?>
				</div>
			</div>
			<div style='border:1px solid #000;'>
				<?php 
				$valor = str_replace('.','',$this->fatura->valor_total);
				print GExtenso::moeda($valor);
				?>
			</div>
		</td>
	</tr>
	<tr>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
	</tr>
	<tr>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
		<td>asdads</td>
	</tr>
	
</table>

